import type { Metadata } from "next";
import { Google_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/widgets/Navbar";

const googleSans = Google_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${googleSans.className} relative antialiased bg-background text-neutral-200`}
      >
        <Navbar />
        <main className="w-full h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
